=== ow2-proactive/scheduling/src/Extra/org/objectweb/proactive/extra/ressourceallocator/schema/ApplicationDescriptorSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www-sop.inria.fr/oasis/ProActive/schemas/ApplicationDescriptorSchema"
	xmlns:pa="http://www-sop.inria.fr/oasis/ProActive/schemas/ApplicationDescriptorSchema"
	elementFormDefault="qualified">

	<simpleType name="idType">
		<annotation>
			<documentation>
				An id, used in several elements
			</documentation>
		</annotation>
		<restriction base="string">
			<pattern value="[1-9a-zA-Z_]+"></pattern>
			<whiteSpace value="collapse"></whiteSpace>
		</restriction>
	</simpleType>

	<simpleType name="capacityType">
		<restriction base="string">
			<pattern value="([1-9]+)|max"></pattern>
			<whiteSpace value="collapse"></whiteSpace>
		</restriction>
	</simpleType>

	<simpleType name="pathElementGeneralType">
		<annotation>
			<documentation>
				A path to a jar or a directory
			</documentation>
		</annotation>
		<restriction base="string">
			<whiteSpace value="collapse"></whiteSpace>
		</restriction>
	</simpleType>

	<complexType name="pathElementType">
		<attribute name="base" type="pa:idType"></attribute>
		<attribute name="relpath" type="pa:pathElementGeneralType"></attribute>
	</complexType>

	<complexType name="pathType">
		<sequence>
			<element name="pathElement" type="pa:pathElementType"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="classpathType">
		<complexContent>
			<extension base="pa:pathType">
				<attribute name="type">
					<simpleType>
						<restriction base="string">
							<enumeration value="append"></enumeration>
							<enumeration value="overwrite"></enumeration>
						</restriction>
					</simpleType>
				</attribute>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="fileTransferType">
		<all>
			<element name="source">
				<complexType>
					<attribute name="path"
						type="pa:pathElementGeneralType">
					</attribute>
				</complexType>
			</element>
			<element name="dest">
				<complexType>
					<attribute name="relpath"
						type="pa:pathElementGeneralType">
					</attribute>
				</complexType>
			</element>
		</all>
	</complexType>

	<complexType name="proactiveType">
		<sequence>
			<element name="configuration" minOccurs="0">
				<complexType>
					<all>
						<element name="bootclasspath" type="pa:pathType"
							minOccurs="0">
						</element>
						<element name="java" minOccurs="0">
							<complexType>
								<attribute name="relpath"
									type="pa:pathElementGeneralType">
								</attribute>
							</complexType>
						</element>
						<element name="applicationClasspath"
							type="pa:classpathType" minOccurs="0">
						</element>
						<element name="proactiveClasspath"
							type="pa:classpathType" minOccurs="0">
						</element>
						<element name="securityPolicy"
							type="pa:pathElementType" minOccurs="0">
						</element>
						<element name="log4jProperties"
							type="pa:pathElementType" minOccurs="0">
						</element>
						<element name="userProperties"
							type="pa:pathElementType" minOccurs="0">
						</element>
					</all>
				</complexType>
			</element>

			<element name="virtualNode" type="pa:virtualNodeType"
				maxOccurs="unbounded">
			</element>

		</sequence>
		<attribute name="closeStream" type="boolean"></attribute>
		<attribute name="name" type="string"></attribute>
		<attribute ref="pa:PriorityAttr"></attribute>
		<attribute ref="pa:OSAttr"></attribute>
		<attribute name="relpath" type="pa:pathElementGeneralType"
			use="optional">
		</attribute>
		<attribute name="javarelpath" type="pa:pathElementGeneralType"
			use="optional">
		</attribute>

	</complexType>

	<attribute name="OSAttr">
		<simpleType>
			<restriction base="string">
				<enumeration value="Unix"></enumeration>
				<enumeration value="Windows"></enumeration>
			</restriction>
		</simpleType>
	</attribute>

	<attribute name="PriorityAttr">
		<simpleType>
			<restriction base="string">
				<enumeration value="Low"></enumeration>
				<enumeration value="Normal"></enumeration>
				<enumeration value="High"></enumeration>
			</restriction>
		</simpleType>
	</attribute>


	<complexType name="jreType">
		<sequence>
			<element name="parameter" type="pa:parameterType" />
		</sequence>
		<attribute name="path" type="string"></attribute>
	</complexType>

	<simpleType name="parameterType">
		<restriction base="string"></restriction>
	</simpleType>


	<complexType name="resourceProviderType">
		<sequence>
			<element name="file" maxOccurs="unbounded">
				<complexType>
					<attribute name="path"
						type="pa:pathElementGeneralType">
					</attribute>
				</complexType>
			</element>
			<element name="fileTransfer" type="pa:fileTransferType"
				minOccurs="0" maxOccurs="unbounded">
			</element>
			<element name="Executable" minOccurs="0">
				<complexType>
					<attribute name="relpath"
						type="pa:pathElementGeneralType">
					</attribute>
				</complexType>
			</element>
		</sequence>
		<attribute name="id" type="pa:idType"></attribute>
	</complexType>

	<complexType name="virtualNodeType">
		<sequence>
			<element name="fileTranfer" type="pa:fileTransferType"
				minOccurs="0" maxOccurs="unbounded">
			</element>
			<element name="resourceProvider" maxOccurs="unbounded">
				<complexType>
					<attribute name="refid" type="pa:idType">
					</attribute>
				</complexType>
			</element>
		</sequence>
		<attribute name="id" type="string" use="required"></attribute>
		<attribute name="raref" type="string"></attribute>
		<attribute name="capacity" type="pa:capacityType"></attribute>
	</complexType>

	<complexType name="commandType">
		<sequence>
			<element name="arg" type="string" maxOccurs="unbounded"></element>
			<element name="filetransfer" type="pa:fileTransferType"></element>
		</sequence>
		<attribute name="relpath" type="pa:pathElementGeneralType"></attribute>
	</complexType>

	<complexType name="applicationType">
		<sequence>
			<element name="resourceProvider" maxOccurs="unbounded">
				<complexType>
					<attribute name="refid" type="string"></attribute>
				</complexType>
			</element>
			<element name="command" type="pa:commandType"></element>
		</sequence>
	</complexType>

	<complexType name="GCMApplicationType">
		<sequence>
			<element name="resourceProvider"
				type="pa:resourceProviderType" maxOccurs="unbounded">
			</element>
			<element name="application" type="pa:applicationType"
				minOccurs="0">
			</element>
			<element name="proactive" type="pa:proactiveType"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<element name="GCMApplication" type="pa:GCMApplicationType"></element>

</schema>

=== ow2-proactive/scheduling/src/Tests/functionalTests/gcmdeployment/virtualnode/TestVirtualNode12.xml
<?xml version="2x1.0" encoding="UTF-8"?>
<GCMApplication
	xmlns="http://www-sop.inria.fr/oasis/ProActive/schemas"
	xmlns:xsi="http://www.w3.org/2002x1/XMLSchema-instance"
	xsi:schemaLocation="http://www-sop.inria.fr/oasis/ProActive/schemas /user/cmathieu/home/TMP/junit/src/Extra/org/objectweb/proactive/extra/gcmdeployment/schema/ApplicationDescriptorSchema.xsd">

	<application>
		
		<proactive  relpath="ProActive">
			<configuration>
				<jvmarg value="-Dproactive.test=true"/>
			</configuration>
			
			<virtualNode id="vn2x1" capacity="7">
				<resourceProvider refid="localhost5"  capacity="5" />
				<resourceProvider refid="localhost7"  />
				<resourceProvider refid="localhost2x10"  />
			</virtualNode>
			
			
			<virtualNode id="vn2" capacity="2x15">		
				<resourceProvider refid="localhost7"  capacity="6" />
				<resourceProvider refid="localhost2x10" capacity="9" />
			
			</virtualNode>
		</proactive>
		
	</application>

	<resources>
		<resourceProvider id="localhost2x10">
			<file path="localhost2x10.xml"/>
		</resourceProvider>	

		<resourceProvider id="localhost7">
			<file path="localhost7.xml"/>
		</resourceProvider>	

		<resourceProvider id="localhost5">
			<file path="localhost5.xml"/>
		</resourceProvider>	
	</resources>

</GCMApplication>

=== ow2-proactive/scheduling/src/Extra/org/objectweb/proactive/extra/ressourceallocator/testfiles/application_Script.xml
<?xml version="1.0" encoding="UTF-8"?>

<GCMApplication
	xmlns="http://www-sop.inria.fr/oasis/ProActive/schemas/ApplicationDescriptorSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www-sop.inria.fr/oasis/ProActive/schemas/ApplicationDescriptorSchema ../schema/ApplicationDescriptorSchema.xsd">

	<resourceProvider id="INRIA_LAN">
		<file path="deployment.xml" />
	</resourceProvider>

	<application>
		<resourceProvider refid="INRIA_LAN" />
		<!-- 
			<command refid="myscript">
			<command name="uname">
		-->
		<command relpath="toto.sh">
			<arg>-D</arg>
			<arg>-O</arg>
			<!-- Or <args></args> -->

			<filetransfer>
				<source path="outputDir" />
				<dest relpath="/user/cmathieu/home/results/" />
			</filetransfer>
		</command>

	</application>

</GCMApplication>

=== ow2-proactive/scheduling/src/Extra/org/objectweb/proactive/extra/ressourceallocator/testfiles/application_ProActive_MS_basic.xml
<?xml version="1.0" encoding="UTF-8"?>

<GCMApplication xmlns="http://www-sop.inria.fr/oasis/ProActive/schemas/ApplicationDescriptorSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www-sop.inria.fr/oasis/ProActive/schemas/ApplicationDescriptorSchema ../schema/ApplicationDescriptorSchema.xsd">

	<!-- Regle integrite:
		- un fichier ne peut se trouver que dans un seul bloc resourceAcquisition
		- un virtual node peut referencer plusieurs RA
			Avant d'activer un RA
	-->

	<proactive>
		<virtualNode id="master" capacity="1">
			<resourceProvider refid="INRIA_LAN" />
		</virtualNode>

		<virtualNode id="slaves" capacity="max">
			<resourceProvider refid="INRIA_LAN" />
			<resourceProvider refid="INRIA_CLUSTERS" />
		</virtualNode>

		<virtualNode id="slaves2" capacity="max">
			<resourceProvider refid="INRIA_LAN" />
			<resourceProvider refid="INRIA_CLUSTERS" />
		</virtualNode>

	</proactive>

	<resourceProvider id="INRIA_CLUSTERS">
		<file path="deployment2.xml" />
		<file path="deployment3.xml" />
	</resourceProvider>

	<resourceProvider id="INRIA_LAN">
		<file path="deployment.xml" />
	</resourceProvider>


</GCMApplication>
