=== ow2-proactive/scheduling/scheduler/scheduler-api/src/main/resources/org/ow2/proactive/scheduler/common/xml/schemas/globalvariables/3.12/globalvariables.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:proactive:globalvariables:3.12" xmlns:jd="urn:proactive:globalvariables:3.12">
  <xs:element name="globalvariables">
    <xs:annotation>
      <xs:documentation>a set of global variables, applying to workflows according to filters</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="jd:filter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="filter">
    <xs:annotation>
      <xs:documentation>Definition of a filter for global variables</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="jd:select"/>
        <xs:element ref="jd:variables"/>
        <xs:element ref="jd:genericInformation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="select">
    <xs:annotation>
      <xs:documentation>select workflows according to criterias</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="jd:xpath"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="xpath" type="xs:string">
    <xs:annotation>
      <xs:documentation>filter workflows based on a xpath expression</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="variables">
    <xs:annotation>
      <xs:documentation>Definition of global variables which will be applied to workflows matching the given xpath expression</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="jd:variable"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="variable">
    <xs:annotation>
      <xs:documentation>Definition of one variable, the variable can be reused (even in another following variable definition) by using the syntax ${name_of_variable}</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attributeGroup ref="jd:variableName"/>
      <xs:attributeGroup ref="jd:variableValue"/>
      <xs:attribute name="model" type="xs:string">
        <xs:annotation>
          <xs:documentation>Model definition of the variable</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="variableName">
    <xs:attribute name="name" use="required" type="xs:NCName">
      <xs:annotation>
        <xs:documentation>Name of a variable</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:attributeGroup name="variableValue">
    <xs:attribute name="value" use="required" type="xs:string">
      <xs:annotation>
        <xs:documentation>The patterns ${variable_name} will be replaced by this value</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:attributeGroup name="variableModel">
    <xs:attribute name="model" use="required" type="xs:string">
      <xs:annotation>
        <xs:documentation>Model definition of the variable</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="genericInformation">
    <xs:annotation>
      <xs:documentation>Definition of any extra information assigned to the workflow</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="jd:info"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="info">
    <xs:annotation>
      <xs:documentation>Extra Information assigned to the workflow</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attributeGroup ref="jd:infoName"/>
      <xs:attributeGroup ref="jd:infoValue"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="infoName">
    <xs:attribute name="name" use="required" type="xs:NCName">
      <xs:annotation>
        <xs:documentation>Name of the information variable</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:attributeGroup name="infoValue">
    <xs:attribute name="value" use="required" type="xs:string">
      <xs:annotation>
        <xs:documentation>Value of the information variable</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>
</xs:schema>

=== ow2-proactive/scheduling/config/scheduler/global_variables.xml
<?xml version="1.0" encoding="UTF-8"?>
<globalvariables
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="urn:proactive:globalvariables:3.13" xsi:schemaLocation="urn:proactive:globalvariables:3.13 http://www.activeeon.com/public_content/schemas/proactive/globalvariables/3.13/globalvariables.xsd">
        <!-- Multiple filters can be added, to apply different set of global variables to different workflows -->
        <filter>
            <select>
                <!-- Xpath expressions are used to filter workflows affected by global variables.
                Example: to select workflows belonging to the basic-examples bucket
                <xpath><![CDATA[/job/genericInformation/info[@name='bucketName' and @value='basic-examples']]]></xpath>
                -->
                <xpath><![CDATA[.]]></xpath>
                <!-- more than one xpath expression can be added. In that case, global variables are applied when all xpath expressions match -->
            </select>
            <!-- add global variables or generic information below -->
            <variables>
            </variables>
            <genericInformation>
            </genericInformation>
        </filter>
        <filter>
            <select>
                <xpath><![CDATA[(/job/genericInformation/info[@name='bucketName' and (@value='ai-auto-ml-optimization' or @value='ai-machine-learning' or @value='ai-machine-learning-workflows' or @value='ai-deep-learning' or @value='ai-deep-learning-workflows' or @value='ai-federated-learning' or @value='ai-model-as-a-service' or @value='ai-data-visualization')])]]></xpath>
            </select>
            <variables>
                <variable name="NATIVE_SCHEDULER" value="" advanced="true" description="Name of the Native Scheduler node source to use when the workflow tasks must be deployed inside a cluster such as SLURM, LSF, etc." group="Resource Management" hidden="false" model="PA:MODEL_FROM_URL(${PA_SCHEDULER_REST_PUBLIC_URL}/rm/model/nodesources)"/>
                <variable name="NATIVE_SCHEDULER_PARAMS" value="" advanced="true" description="Parameters given to the native scheduler (SLURM, LSF, etc) while requesting a ProActive node used to deploy the workflow tasks." group="Resource Management" hidden="false"/>
                <variable name="NODE_ACCESS_TOKEN" value="" advanced="true" description="If not empty, the workflow tasks will be run only on nodes that contains the specified token." group="Resource Management" hidden="false" model="PA:MODEL_FROM_URL(${PA_SCHEDULER_REST_PUBLIC_URL}/rm/model/tokens)"/>
                <variable name="NODE_SOURCE_NAME" value="" advanced="true" description="If not empty, the workflow tasks will be run only on nodes belonging to the specified node source." group="Resource Management" hidden="false" model="PA:MODEL_FROM_URL(${PA_SCHEDULER_REST_PUBLIC_URL}/rm/model/nodesources)"/>
            </variables>
            <genericInformation>
                <info name="NODESOURCENAME" value="$NODE_SOURCE_NAME"/>
                <info name="NS" value="$NATIVE_SCHEDULER"/>
                <info name="NODE_ACCESS_TOKEN" value="$NODE_ACCESS_TOKEN"/>
                <info name="NS_BATCH" value="$NATIVE_SCHEDULER_PARAMS"/>
                <info name="PYTHON_COMMAND" value="python3"/>
            </genericInformation>
        </filter>
        <filter>
            <select>
                <xpath><![CDATA[(/job/genericInformation/info[@name='bucketName' and @value='service-automation']) and (/job/genericInformation/info[@name='pca.states' and @value='(VOID,RUNNING)'])]]></xpath>
            </select>
            <variables>
                <variable name="NATIVE_SCHEDULER" value="" advanced="true" description="Name of the Native Scheduler node source to use when the workflow tasks must be deployed inside a cluster such as SLURM, LSF, etc." group="Resource Management" hidden="false" model="PA:MODEL_FROM_URL(${PA_SCHEDULER_REST_PUBLIC_URL}/rm/model/nodesources)"/>
                <variable name="NATIVE_SCHEDULER_PARAMS" value="" advanced="true" description="Parameters given to the native scheduler (SLURM, LSF, etc) while requesting a ProActive node used to deploy the workflow tasks." group="Resource Management" hidden="false"/>
                <variable name="NODE_ACCESS_TOKEN" value="" advanced="true" description="If not empty, the workflow tasks will be run only on nodes that contains the specified token." group="Resource Management" hidden="false" model="PA:MODEL_FROM_URL(${PA_SCHEDULER_REST_PUBLIC_URL}/rm/model/tokens)"/>
                <variable name="NODE_SOURCE_NAME" value="" advanced="true" description="If not empty, the workflow tasks will be run only on nodes belonging to the specified node source." group="Resource Management" hidden="false" model="PA:MODEL_FROM_URL(${PA_SCHEDULER_REST_PUBLIC_URL}/rm/model/nodesources)"/>
            </variables>
            <genericInformation>
                <info name="NODESOURCENAME" value="$NODE_SOURCE_NAME"/>
                <info name="NS" value="$NATIVE_SCHEDULER"/>
                <info name="NODE_ACCESS_TOKEN" value="$NODE_ACCESS_TOKEN"/>
                <info name="NS_BATCH" value="$NATIVE_SCHEDULER_PARAMS"/>
                <info name="PYTHON_COMMAND" value="python3"/>
            </genericInformation>
        </filter>
        <filter>
            <select>
                <xpath><![CDATA[/job/genericInformation/info[@name='pca.states' and @value!='(VOID,RUNNING)']]]></xpath>
            </select>
            <variables>
            </variables>
            <genericInformation>
                <info name="NODESOURCENAME" value="$NODE_SOURCE_NAME"/>
                <info name="NS" value="$NATIVE_SCHEDULER"/>
                <info name="NS_BATCH" value="$NATIVE_SCHEDULER_PARAMS"/>
            </genericInformation>
        </filter>
</globalvariables>
